//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace labaratorija
{
    using System;
    using System.Collections.Generic;
    
    public partial class profili
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public profili()
        {
            this.koraciigracas = new HashSet<koraciigraca>();
        }
    
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<int> poeni { get; set; }
        public string ImeiPrez { get; set; }
        public string Fakultet { get; set; }
        public string Smer { get; set; }
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<koraciigraca> koraciigracas { get; set; }
        public virtual profili profili1 { get; set; }
        public virtual profili profili2 { get; set; }
    }
}
